insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '1','user','John Normal','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe','')
insert into user_roles (user_id, roles) values ('1', 'USER')
insert into application_user (version, id, username,name,hashed_password,profile_picture) values (1, '2','admin','Emma Executive','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.','')
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('2', 'ADMIN')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','jigrormo','1955-11-07','Insurance Clerk','1955-11-07','1955-11-07')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','zun','2014-11-07','Mortarman','2014-11-07','2014-11-07')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','capfad','1974-10-23','Beer Coil Cleaner','1974-10-23','1974-10-23')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','dec','2014-12-10','Scale Attendant','2014-12-10','2014-12-10')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','bivo','1973-02-06','Clinical Audiologist','1973-02-06','1973-02-06')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','judbilo','1938-11-04','Parking Meter Collector','1938-11-04','1938-11-04')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','joraf','1968-06-08','Business Unit Manager','1968-06-08','1968-06-08')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','kem','2011-04-19','Technical Communicator','2011-04-19','2011-04-19')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','odeter','1960-06-23','Correctional Officer Sergeant','1960-06-23','1960-06-23')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','lisohuje','1947-05-31','Food Chemist','1947-05-31','1947-05-31')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','duod','1983-07-12','Signals Intelligence/Electronic Warfare Chief','1983-07-12','1983-07-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','nowufpus','1944-05-12','Language Pathologist','1944-05-12','1944-05-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','kagu','1959-05-12','Wildlife Officer','1959-05-12','1959-05-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','fef','2010-02-20','Bindery Machine Operator','2010-02-20','2010-02-20')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','derwogi','1931-02-16','Instructional Aide','1931-02-16','1931-02-16')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','wehovuce','1950-07-26','Clinical Psychiatrist','1950-07-26','1950-07-26')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','zamum','1976-05-21','Mortician Investigator','1976-05-21','1976-05-21')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','dunebuh','1950-09-16','Rod Buster Helper','1950-09-16','1950-09-16')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','repiwid','1933-10-09','Classroom Aide','1933-10-09','1933-10-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','razuppa','1935-04-21','Traditional Chinese Herbalist','1935-04-21','1935-04-21')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','kulmenim','1951-09-22','Electronic Drafter','1951-09-22','1951-09-22')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','ib','2016-02-14','Vault Teller','2016-02-14','2016-02-14')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','ba','1997-03-01','Fire Sprinkler Installer','1997-03-01','1997-03-01')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','tohhij','1975-09-03','Brewery Pumper','1975-09-03','1975-09-03')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','tuvo','1988-10-21','Kitchen Chef','1988-10-21','1988-10-21')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','foga','1967-12-13','Medical Esthetician','1967-12-13','1967-12-13')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','uswuzzub','1937-05-18','Auto Tire Worker','1937-05-18','1937-05-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','hivwerip','1934-08-26','Semi-Truck Driver','1934-08-26','1934-08-26')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','gugusu','1948-07-09','Command And Control','1948-07-09','1948-07-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','zedekak','1930-08-22','Drywall Hanger','1930-08-22','1930-08-22')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 31,'Jay','Blake','jay.blake@ral.mk','ral','2010-09-09','Real Property Evaluator','2010-09-09','2010-09-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','turuhu','1974-09-17','Human Performance Professor','1974-09-17','1974-09-17')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','omjo','1960-04-05','V/Stol Landing Signal Officer','1960-04-05','1960-04-05')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','rig','1994-02-09','Air Control/Anti-Air Warfare Officer','1994-02-09','1994-02-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','sicewap','1945-10-06','General Superintendent','1945-10-06','1945-10-06')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','fo','2015-10-31','Child Protective Services Social Worker','2015-10-31','2015-10-31')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','gegijap','1946-08-14','Lens Grinder and Polisher','1946-08-14','1946-08-14')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','kuvesa','1942-03-02','Civil Engineering Professor','1942-03-02','1942-03-02')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','lapahu','1931-06-12','Mobile Home Servicer','1931-06-12','1931-06-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','zev','1993-05-16','Floor Refinisher','1993-05-16','1993-05-16')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','nabeaga','1956-08-07','Senior Sales Associate','1956-08-07','1956-08-07')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','kaot','1989-10-10','Tile Designer','1989-10-10','1989-10-10')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','tawuctuj','1942-11-19','Econometrics Professor','1942-11-19','1942-11-19')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','eh','1995-09-12','Basketball Player','1995-09-12','1995-09-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','fajjusuz','1935-09-03','Indirect Fire Infantryman','1935-09-03','1935-09-03')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','pave','1965-09-16','Licensed Esthetician','1965-09-16','1965-09-16')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','ispaviw','1958-07-15','Antisubmarine Warfare Intelligence Officer','1958-07-15','1958-07-15')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','ha','2020-03-10','Research Assistant','2020-03-10','2020-03-10')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','iliat','1959-09-20','Cigar Roller','1959-09-20','1959-09-20')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','do','2010-07-09','Customer Support Representative','2010-07-09','2010-07-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 51,'Richard','Silva','richard.silva@wi.lc','wi','2016-02-18','Programmer','2016-02-18','2016-02-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','iwage','1979-06-24','Global Engineering Manager','1979-06-24','1979-06-24')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','joopoju','1945-04-17','Telegraph and Teletype Operator','1945-04-17','1945-04-17')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','gojawu','1989-09-24','Hairpiece Stylist','1989-09-24','1989-09-24')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','afigoh','1975-03-15','Tobacco Buyer','1975-03-15','1975-03-15')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 56,'Lula','Testi','lula.testi@benom.tj','benom','1973-01-09','Marine Steamfitter','1973-01-09','1973-01-09')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','jevakbe','1930-06-20','Attending Anesthesiologist','1930-06-20','1930-06-20')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','darhow','1969-03-20','Certified Indoor Environmentalist','1969-03-20','1969-03-20')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','dupid','1973-01-30','Land Management Forester','1973-01-30','1973-01-30')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','comouc','1937-11-07','Digital Proofing and Platemaker','1937-11-07','1937-11-07')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','igunisi','1943-03-03','Public Health Veterinarian','1943-03-03','1943-03-03')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 62,'Joe','Riley','joe.riley@pe.vu','pe','2018-08-11','Statement Processor','2018-08-11','2018-08-11')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','puk','2012-05-27','Computer Applications Developer','2012-05-27','2012-05-27')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','vegub','1971-03-20','African History Professor','1971-03-20','1971-03-20')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','rucwi','1983-06-23','Gastroenterology Professor','1983-06-23','1983-06-23')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','agijit','1974-04-15','Laboratory Animal Caretaker','1974-04-15','1974-04-15')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','loolu','1983-03-17','Water Pump Installer','1983-03-17','1983-03-17')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','tupwovali','1950-12-27','Orthopedic Cast Specialist','1950-12-27','1950-12-27')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','hidge','1971-04-29','Budget Coordinator','1971-04-29','1971-04-29')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','liowci','1949-10-08','Railroad Engineer','1949-10-08','1949-10-08')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','vesa','1985-04-12','Chief Projectionist','1985-04-12','1985-04-12')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','wupikdoh','1928-09-29','Telecasting Engineer','1928-09-29','1928-09-29')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','dajsiphaj','1936-10-10','Drama Therapist','1936-10-10','1936-10-10')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','soofpe','1956-07-18','General Superintendent','1956-07-18','1956-07-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','aruzusjas','1938-09-19','Technical Communicator','1938-09-19','1938-09-19')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','ufeco','1964-07-05','Leisure Studies Professor','1964-07-05','1964-07-05')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','uneehi','1960-01-06','Air Conditioning Service Technician','1960-01-06','1960-01-06')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','hahinaba','1930-10-01','Business Unit Manager','1930-10-01','1930-10-01')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 79,'Rodney','Love','rodney.love@zun.ph','zun','2014-01-25','Job Estimator','2014-01-25','2014-01-25')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','jo','2003-01-17','Correctional Officer Sergeant','2003-01-17','2003-01-17')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','goltuefo','1940-09-18','Parking Meter Collector','1940-09-18','1940-09-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','lupuwuzo','1932-06-15','Signals Intelligence/Electronic Warfare Chief','1932-06-15','1932-06-15')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','reduzris','1929-06-27','Clinical Psychiatrist','1929-06-27','1929-06-27')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','pubsav','1982-09-30','Wildlife Officer','1982-09-30','1982-09-30')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','lullip','1975-03-10','Food Chemist','1975-03-10','1975-03-10')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','aba','2014-05-14','Advanced Foreign Counterintelligence Specialist (Afcs)','2014-05-14','2014-05-14')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','kettujwo','1941-03-06','Forest Fire Officer','1941-03-06','1941-03-06')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','ju','2015-06-19','Catalogue Illustrator','2015-06-19','2015-06-19')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','vioburez','1947-05-14','Knife Grinder','1947-05-14','1947-05-14')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','ig','2002-03-05','Neuropsychiatrist','2002-03-05','2002-03-05')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','omu','2003-08-16','Bottle Packer','2003-08-16','2003-08-16')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','luw','2020-08-18','Special Education Kindergarten Teacher','2020-08-18','2020-08-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','pi','2010-01-25','Commercial Art Instructor','2010-01-25','2010-01-25')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 94,'Craig','Russell','craig.russell@zu.nz','zu','2021-11-22','Ferryboat Captain','2021-11-22','2021-11-22')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 95,'John','Sutton','john.sutton@ag.ee','ag','2015-02-03','School Social Worker','2015-02-03','2015-02-03')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','fopav','1992-01-18','Joint Terminal Attack Controller','1992-01-18','1992-01-18')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 97,'Gary','Baker','gary.baker@ji.cf','ji','2024-02-07','VP Sales','2024-02-07','2024-02-07')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','lojet','1989-06-17','Auto Service Station Attendant','1989-06-17','1989-06-17')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','ukve','1970-10-30','Healthcare Social Worker','1970-10-30','1970-10-30')
insert into panelist(version, id,first_name,last_name,email,phone,date_of_birth,occupation,last_contacted,last_interviewed) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','viipo','1972-11-18','Comedian','1972-11-18','1972-11-18')
insert into panel(version, id,name,created,active) values (1, 1,'jigrormo','1955-11-07',false)
insert into panel(version, id,name,created,active) values (1, 2,'zun','2014-11-07',true)
insert into panel(version, id,name,created,active) values (1, 3,'capfad','1974-10-23',false)
insert into panel(version, id,name,created,active) values (1, 4,'dec','2014-12-10',true)
insert into panel(version, id,name,created,active) values (1, 5,'bivo','1973-02-06',false)
insert into panel(version, id,name,created,active) values (1, 6,'judbilo','1938-11-04',false)
insert into panel(version, id,name,created,active) values (1, 7,'joraf','1968-06-08',false)
insert into panel(version, id,name,created,active) values (1, 8,'kem','2011-04-19',true)
insert into panel(version, id,name,created,active) values (1, 9,'odeter','1960-06-23',false)
insert into panel(version, id,name,created,active) values (1, 10,'lisohuje','1947-05-31',false)
insert into panel(version, id,name,created,active) values (1, 11,'duod','1983-07-12',true)
insert into panel(version, id,name,created,active) values (1, 12,'nowufpus','1944-05-12',false)
insert into panel(version, id,name,created,active) values (1, 13,'kagu','1959-05-12',false)
insert into panel(version, id,name,created,active) values (1, 14,'fef','2010-02-20',true)
insert into panel(version, id,name,created,active) values (1, 15,'derwogi','1931-02-16',false)
insert into panel(version, id,name,created,active) values (1, 16,'wehovuce','1950-07-26',false)
insert into panel(version, id,name,created,active) values (1, 17,'zamum','1976-05-21',true)
insert into panel(version, id,name,created,active) values (1, 18,'dunebuh','1950-09-16',false)
insert into panel(version, id,name,created,active) values (1, 19,'repiwid','1933-10-09',false)
insert into panel(version, id,name,created,active) values (1, 20,'razuppa','1935-04-21',false)
insert into panel(version, id,name,created,active) values (1, 21,'kulmenim','1951-09-22',false)
insert into panel(version, id,name,created,active) values (1, 22,'ib','2016-02-14',true)
insert into panel(version, id,name,created,active) values (1, 23,'ba','1997-03-01',true)
insert into panel(version, id,name,created,active) values (1, 24,'tohhij','1975-09-03',true)
insert into panel(version, id,name,created,active) values (1, 25,'tuvo','1988-10-21',true)
insert into panel(version, id,name,created,active) values (1, 26,'foga','1967-12-13',false)
insert into panel(version, id,name,created,active) values (1, 27,'uswuzzub','1937-05-18',false)
insert into panel(version, id,name,created,active) values (1, 28,'hivwerip','1934-08-26',false)
insert into panel(version, id,name,created,active) values (1, 29,'gugusu','1948-07-09',false)
insert into panel(version, id,name,created,active) values (1, 30,'zedekak','1930-08-22',false)
insert into panel(version, id,name,created,active) values (1, 31,'ral','2010-09-09',true)
insert into panel(version, id,name,created,active) values (1, 32,'turuhu','1974-09-17',false)
insert into panel(version, id,name,created,active) values (1, 33,'omjo','1960-04-05',false)
insert into panel(version, id,name,created,active) values (1, 34,'rig','1994-02-09',true)
insert into panel(version, id,name,created,active) values (1, 35,'sicewap','1945-10-06',false)
insert into panel(version, id,name,created,active) values (1, 36,'fo','2015-10-31',true)
insert into panel(version, id,name,created,active) values (1, 37,'gegijap','1946-08-14',false)
insert into panel(version, id,name,created,active) values (1, 38,'kuvesa','1942-03-02',false)
insert into panel(version, id,name,created,active) values (1, 39,'lapahu','1931-06-12',false)
insert into panel(version, id,name,created,active) values (1, 40,'zev','1993-05-16',true)
insert into panel(version, id,name,created,active) values (1, 41,'nabeaga','1956-08-07',false)
insert into panel(version, id,name,created,active) values (1, 42,'kaot','1989-10-10',true)
insert into panel(version, id,name,created,active) values (1, 43,'tawuctuj','1942-11-19',false)
insert into panel(version, id,name,created,active) values (1, 44,'eh','1995-09-12',true)
insert into panel(version, id,name,created,active) values (1, 45,'fajjusuz','1935-09-03',false)
insert into panel(version, id,name,created,active) values (1, 46,'pave','1965-09-16',false)
insert into panel(version, id,name,created,active) values (1, 47,'ispaviw','1958-07-15',false)
insert into panel(version, id,name,created,active) values (1, 48,'ha','2020-03-10',true)
insert into panel(version, id,name,created,active) values (1, 49,'iliat','1959-09-20',false)
insert into panel(version, id,name,created,active) values (1, 50,'do','2010-07-09',true)
insert into panel(version, id,name,created,active) values (1, 51,'wi','2016-02-18',true)
insert into panel(version, id,name,created,active) values (1, 52,'iwage','1979-06-24',true)
insert into panel(version, id,name,created,active) values (1, 53,'joopoju','1945-04-17',false)
insert into panel(version, id,name,created,active) values (1, 54,'gojawu','1989-09-24',true)
insert into panel(version, id,name,created,active) values (1, 55,'afigoh','1975-03-15',false)
insert into panel(version, id,name,created,active) values (1, 56,'benom','1973-01-09',false)
insert into panel(version, id,name,created,active) values (1, 57,'jevakbe','1930-06-20',false)
insert into panel(version, id,name,created,active) values (1, 58,'darhow','1969-03-20',false)
insert into panel(version, id,name,created,active) values (1, 59,'dupid','1973-01-30',false)
insert into panel(version, id,name,created,active) values (1, 60,'comouc','1937-11-07',false)
insert into panel(version, id,name,created,active) values (1, 61,'igunisi','1943-03-03',false)
insert into panel(version, id,name,created,active) values (1, 62,'pe','2018-08-11',true)
insert into panel(version, id,name,created,active) values (1, 63,'puk','2012-05-27',true)
insert into panel(version, id,name,created,active) values (1, 64,'vegub','1971-03-20',false)
insert into panel(version, id,name,created,active) values (1, 65,'rucwi','1983-06-23',true)
insert into panel(version, id,name,created,active) values (1, 66,'agijit','1974-04-15',false)
insert into panel(version, id,name,created,active) values (1, 67,'loolu','1983-03-17',true)
insert into panel(version, id,name,created,active) values (1, 68,'tupwovali','1950-12-27',false)
insert into panel(version, id,name,created,active) values (1, 69,'hidge','1971-04-29',false)
insert into panel(version, id,name,created,active) values (1, 70,'liowci','1949-10-08',false)
insert into panel(version, id,name,created,active) values (1, 71,'vesa','1985-04-12',true)
insert into panel(version, id,name,created,active) values (1, 72,'wupikdoh','1928-09-29',false)
insert into panel(version, id,name,created,active) values (1, 73,'dajsiphaj','1936-10-10',false)
insert into panel(version, id,name,created,active) values (1, 74,'soofpe','1956-07-18',false)
insert into panel(version, id,name,created,active) values (1, 75,'aruzusjas','1938-09-19',false)
insert into panel(version, id,name,created,active) values (1, 76,'ufeco','1964-07-05',false)
insert into panel(version, id,name,created,active) values (1, 77,'uneehi','1960-01-06',false)
insert into panel(version, id,name,created,active) values (1, 78,'hahinaba','1930-10-01',false)
insert into panel(version, id,name,created,active) values (1, 79,'zun','2014-01-25',true)
insert into panel(version, id,name,created,active) values (1, 80,'jo','2003-01-17',true)
insert into panel(version, id,name,created,active) values (1, 81,'goltuefo','1940-09-18',false)
insert into panel(version, id,name,created,active) values (1, 82,'lupuwuzo','1932-06-15',false)
insert into panel(version, id,name,created,active) values (1, 83,'reduzris','1929-06-27',false)
insert into panel(version, id,name,created,active) values (1, 84,'pubsav','1982-09-30',true)
insert into panel(version, id,name,created,active) values (1, 85,'lullip','1975-03-10',false)
insert into panel(version, id,name,created,active) values (1, 86,'aba','2014-05-14',true)
insert into panel(version, id,name,created,active) values (1, 87,'kettujwo','1941-03-06',false)
insert into panel(version, id,name,created,active) values (1, 88,'ju','2015-06-19',true)
insert into panel(version, id,name,created,active) values (1, 89,'vioburez','1947-05-14',false)
insert into panel(version, id,name,created,active) values (1, 90,'ig','2002-03-05',true)
insert into panel(version, id,name,created,active) values (1, 91,'omu','2003-08-16',true)
insert into panel(version, id,name,created,active) values (1, 92,'luw','2020-08-18',true)
insert into panel(version, id,name,created,active) values (1, 93,'pi','2010-01-25',true)
insert into panel(version, id,name,created,active) values (1, 94,'zu','2021-11-22',true)
insert into panel(version, id,name,created,active) values (1, 95,'ag','2015-02-03',true)
insert into panel(version, id,name,created,active) values (1, 96,'fopav','1992-01-18',true)
insert into panel(version, id,name,created,active) values (1, 97,'ji','2024-02-07',true)
insert into panel(version, id,name,created,active) values (1, 98,'lojet','1989-06-17',true)
insert into panel(version, id,name,created,active) values (1, 99,'ukve','1970-10-30',false)
insert into panel(version, id,name,created,active) values (1, 100,'viipo','1972-11-18',false)
insert into panelist_property(version, id,name,type) values (1, 1,'jigrormo','jigrormo')
insert into panelist_property(version, id,name,type) values (1, 2,'zun','zun')
insert into panelist_property(version, id,name,type) values (1, 3,'capfad','capfad')
insert into panelist_property(version, id,name,type) values (1, 4,'dec','dec')
insert into panelist_property(version, id,name,type) values (1, 5,'bivo','bivo')
insert into panelist_property(version, id,name,type) values (1, 6,'judbilo','judbilo')
insert into panelist_property(version, id,name,type) values (1, 7,'joraf','joraf')
insert into panelist_property(version, id,name,type) values (1, 8,'kem','kem')
insert into panelist_property(version, id,name,type) values (1, 9,'odeter','odeter')
insert into panelist_property(version, id,name,type) values (1, 10,'lisohuje','lisohuje')
insert into panelist_property(version, id,name,type) values (1, 11,'duod','duod')
insert into panelist_property(version, id,name,type) values (1, 12,'nowufpus','nowufpus')
insert into panelist_property(version, id,name,type) values (1, 13,'kagu','kagu')
insert into panelist_property(version, id,name,type) values (1, 14,'fef','fef')
insert into panelist_property(version, id,name,type) values (1, 15,'derwogi','derwogi')
insert into panelist_property(version, id,name,type) values (1, 16,'wehovuce','wehovuce')
insert into panelist_property(version, id,name,type) values (1, 17,'zamum','zamum')
insert into panelist_property(version, id,name,type) values (1, 18,'dunebuh','dunebuh')
insert into panelist_property(version, id,name,type) values (1, 19,'repiwid','repiwid')
insert into panelist_property(version, id,name,type) values (1, 20,'razuppa','razuppa')
insert into panelist_property(version, id,name,type) values (1, 21,'kulmenim','kulmenim')
insert into panelist_property(version, id,name,type) values (1, 22,'ib','ib')
insert into panelist_property(version, id,name,type) values (1, 23,'ba','ba')
insert into panelist_property(version, id,name,type) values (1, 24,'tohhij','tohhij')
insert into panelist_property(version, id,name,type) values (1, 25,'tuvo','tuvo')
insert into panelist_property(version, id,name,type) values (1, 26,'foga','foga')
insert into panelist_property(version, id,name,type) values (1, 27,'uswuzzub','uswuzzub')
insert into panelist_property(version, id,name,type) values (1, 28,'hivwerip','hivwerip')
insert into panelist_property(version, id,name,type) values (1, 29,'gugusu','gugusu')
insert into panelist_property(version, id,name,type) values (1, 30,'zedekak','zedekak')
insert into panelist_property(version, id,name,type) values (1, 31,'ral','ral')
insert into panelist_property(version, id,name,type) values (1, 32,'turuhu','turuhu')
insert into panelist_property(version, id,name,type) values (1, 33,'omjo','omjo')
insert into panelist_property(version, id,name,type) values (1, 34,'rig','rig')
insert into panelist_property(version, id,name,type) values (1, 35,'sicewap','sicewap')
insert into panelist_property(version, id,name,type) values (1, 36,'fo','fo')
insert into panelist_property(version, id,name,type) values (1, 37,'gegijap','gegijap')
insert into panelist_property(version, id,name,type) values (1, 38,'kuvesa','kuvesa')
insert into panelist_property(version, id,name,type) values (1, 39,'lapahu','lapahu')
insert into panelist_property(version, id,name,type) values (1, 40,'zev','zev')
insert into panelist_property(version, id,name,type) values (1, 41,'nabeaga','nabeaga')
insert into panelist_property(version, id,name,type) values (1, 42,'kaot','kaot')
insert into panelist_property(version, id,name,type) values (1, 43,'tawuctuj','tawuctuj')
insert into panelist_property(version, id,name,type) values (1, 44,'eh','eh')
insert into panelist_property(version, id,name,type) values (1, 45,'fajjusuz','fajjusuz')
insert into panelist_property(version, id,name,type) values (1, 46,'pave','pave')
insert into panelist_property(version, id,name,type) values (1, 47,'ispaviw','ispaviw')
insert into panelist_property(version, id,name,type) values (1, 48,'ha','ha')
insert into panelist_property(version, id,name,type) values (1, 49,'iliat','iliat')
insert into panelist_property(version, id,name,type) values (1, 50,'do','do')
insert into panelist_property(version, id,name,type) values (1, 51,'wi','wi')
insert into panelist_property(version, id,name,type) values (1, 52,'iwage','iwage')
insert into panelist_property(version, id,name,type) values (1, 53,'joopoju','joopoju')
insert into panelist_property(version, id,name,type) values (1, 54,'gojawu','gojawu')
insert into panelist_property(version, id,name,type) values (1, 55,'afigoh','afigoh')
insert into panelist_property(version, id,name,type) values (1, 56,'benom','benom')
insert into panelist_property(version, id,name,type) values (1, 57,'jevakbe','jevakbe')
insert into panelist_property(version, id,name,type) values (1, 58,'darhow','darhow')
insert into panelist_property(version, id,name,type) values (1, 59,'dupid','dupid')
insert into panelist_property(version, id,name,type) values (1, 60,'comouc','comouc')
insert into panelist_property(version, id,name,type) values (1, 61,'igunisi','igunisi')
insert into panelist_property(version, id,name,type) values (1, 62,'pe','pe')
insert into panelist_property(version, id,name,type) values (1, 63,'puk','puk')
insert into panelist_property(version, id,name,type) values (1, 64,'vegub','vegub')
insert into panelist_property(version, id,name,type) values (1, 65,'rucwi','rucwi')
insert into panelist_property(version, id,name,type) values (1, 66,'agijit','agijit')
insert into panelist_property(version, id,name,type) values (1, 67,'loolu','loolu')
insert into panelist_property(version, id,name,type) values (1, 68,'tupwovali','tupwovali')
insert into panelist_property(version, id,name,type) values (1, 69,'hidge','hidge')
insert into panelist_property(version, id,name,type) values (1, 70,'liowci','liowci')
insert into panelist_property(version, id,name,type) values (1, 71,'vesa','vesa')
insert into panelist_property(version, id,name,type) values (1, 72,'wupikdoh','wupikdoh')
insert into panelist_property(version, id,name,type) values (1, 73,'dajsiphaj','dajsiphaj')
insert into panelist_property(version, id,name,type) values (1, 74,'soofpe','soofpe')
insert into panelist_property(version, id,name,type) values (1, 75,'aruzusjas','aruzusjas')
insert into panelist_property(version, id,name,type) values (1, 76,'ufeco','ufeco')
insert into panelist_property(version, id,name,type) values (1, 77,'uneehi','uneehi')
insert into panelist_property(version, id,name,type) values (1, 78,'hahinaba','hahinaba')
insert into panelist_property(version, id,name,type) values (1, 79,'zun','zun')
insert into panelist_property(version, id,name,type) values (1, 80,'jo','jo')
insert into panelist_property(version, id,name,type) values (1, 81,'goltuefo','goltuefo')
insert into panelist_property(version, id,name,type) values (1, 82,'lupuwuzo','lupuwuzo')
insert into panelist_property(version, id,name,type) values (1, 83,'reduzris','reduzris')
insert into panelist_property(version, id,name,type) values (1, 84,'pubsav','pubsav')
insert into panelist_property(version, id,name,type) values (1, 85,'lullip','lullip')
insert into panelist_property(version, id,name,type) values (1, 86,'aba','aba')
insert into panelist_property(version, id,name,type) values (1, 87,'kettujwo','kettujwo')
insert into panelist_property(version, id,name,type) values (1, 88,'ju','ju')
insert into panelist_property(version, id,name,type) values (1, 89,'vioburez','vioburez')
insert into panelist_property(version, id,name,type) values (1, 90,'ig','ig')
insert into panelist_property(version, id,name,type) values (1, 91,'omu','omu')
insert into panelist_property(version, id,name,type) values (1, 92,'luw','luw')
insert into panelist_property(version, id,name,type) values (1, 93,'pi','pi')
insert into panelist_property(version, id,name,type) values (1, 94,'zu','zu')
insert into panelist_property(version, id,name,type) values (1, 95,'ag','ag')
insert into panelist_property(version, id,name,type) values (1, 96,'fopav','fopav')
insert into panelist_property(version, id,name,type) values (1, 97,'ji','ji')
insert into panelist_property(version, id,name,type) values (1, 98,'lojet','lojet')
insert into panelist_property(version, id,name,type) values (1, 99,'ukve','ukve')
insert into panelist_property(version, id,name,type) values (1, 100,'viipo','viipo')
